services:
  wordpress:
    depends_on:
      - db
    image: wordpress:7.1
    restart: always
    volumes:
      - ./fichiers-wordpress:/var/www/html
    ports:
      - 8082:80
    networks:
      - myNetwork
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./database:/var/lib/mysql
      - ./base-de-donnees.sql:/docker-entrypoint-initdb.d/base-de-donnees.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_MOT_DE_PASSE_ROOT}
      MYSQL_DATABASE: cornucopia
      MYSQL_USER: ${MYSQL_UTILISATEUR}
      MYSQL_PASSWORD: ${MYSQL_MOT_DE_PASSE}
    networks:
      - myNetwork
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8083:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: racine-potager-2026
    networks:
      - myNetwork
networks:
  myNetwork: